/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.rivetlogic.suggestionbox.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.rivetlogic.suggestionbox.model.Suggestion;
import com.rivetlogic.suggestionbox.service.SuggestionLocalServiceUtil;

/**
 * The extended model base implementation for the Suggestion service. Represents a row in the &quot;rivetlogic_suggestion_box_Suggestion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SuggestionImpl}.
 * </p>
 *
 * @author Manrique Varela
 * @see SuggestionImpl
 * @see com.rivetlogic.suggestionbox.model.Suggestion
 * @generated
 */
public abstract class SuggestionBaseImpl extends SuggestionModelImpl
	implements Suggestion {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a suggestion model instance should use the {@link Suggestion} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			SuggestionLocalServiceUtil.addSuggestion(this);
		}
		else {
			SuggestionLocalServiceUtil.updateSuggestion(this);
		}
	}
}